Custom labels
criticalstack/crit pull request #29
Opened 2020-12-16 15:09 UTC by levinedan

Apologies for the PR on this repo. In the future I will open a fork and use that to PR.

This change will add the functionality to add labels to the controller manager, kube scheduler, and api-server static pods. 

Testing:
Created a local cinder cluster with the updated crit binary. Specified a config with an extra label and verified it appeared on the pod.

Milan and I also discussed potentially adding a "global" value that would apply a specific label to all static manifests. If you would like to see this functionality please let me know and I can add it before we pull this in.

2020-12-16 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/criticalstack/crit?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/criticalstack/crit?pullRequest=29) before we can accept your contribution.<br/><hr/>**Levine** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/criticalstack/crit?pullRequest=29) it.</sub>

2020-12-17 14:57 UTC, rbtr requested changes
thanks for the contrib - looks like we could make a couple small changes to simplify and otherwise it looks good to me. can you do a rebase while you're updating?

2020-12-17 14:57 UTC, rbtr commented on pkg/cluster/components/apiserver.go
> +	if err := appendExtraLabels(p, cfg.KubeAPIServerConfiguration.ExtraLabels); err != nil {
this function can never return an error, right? so we can drop all of this checking/logging

2020-12-17 14:57 UTC, rbtr commented on pkg/cluster/components/components.go
> +func appendExtraLabels(p *corev1.Pod, labels map[string]string) (err error) {
likewise, since there's no error returned so we can drop it from this signature

2020-12-17 14:57 UTC, rbtr commented on pkg/cluster/components/components.go
> +func appendExtraLabels(p *corev1.Pod, labels map[string]string) (err error) {
style nit, but can you move this up to be with the other append function in the file?

2020-12-17 15:56 UTC, rbtr approved these changes
looks good thanks

2020-12-17 16:44 UTC, merged

2020-12-18 19:04 UTC, ChrisRx commented
@rbtr @levinedan a couple issues with this one:

* v1alpha1 shouldn't have the new field (rather conversions.go should be updated)
* Whenever changes are made to any of the configs, you need to run `make update-codegen` when working with anything related to k8s that uses code-generator.  This ensures that the defaulting and conversion functions are generated with the new changes.

I don't think we need to revert the commit, but a release should not be tagged until the changes are fixed.