change cert-dir to kube-dir
criticalstack/crit pull request #33
Opened 2021-01-25 21:50 UTC by seaunderwater

This addresses https://github.com/criticalstack/crit/issues/14 where the `crit certs renew` command fails. 

Changes: 
* `crit certs renew`:  takes `--kube-dir` flag instead of `--cert-dir`
* `crit certs list`: the same issue was present for this command, so this now also takes the `--kube-dir` flag

2021-01-25 22:40 UTC, rbtr approved these changes, later dismissed
since we are internally setting the certs-dir to the `kube-dir` + `/pki` during node bootstrap, this seems reasonable to me 👍🏼

2021-01-27 15:29 UTC, ktravis requested changes
This looks good but I might prefer if it was still possible to override the cert directory (rather than as-is always including the `/pki/` in the path. I think this change is probably fine beyond that, though the flag should have a help string to indicate that behavior.

2021-02-01 18:02 UTC, ChrisRx approved these changes, later dismissed
lgtm

2021-02-03 18:03 UTC, seaunderwater commented
> This looks good but I might prefer if it was still possible to override the cert directory (rather than as-is always including the `/pki/` in the path. I think this change is probably fine beyond that, though the flag should have a help string to indicate that behavior.

I added the helper, so the output looks like this: 
```
$ crit certs renew -h
renew cluster certificates

Usage:
  crit certs renew [flags]

Flags:
      --dry-run           
  -h, --help              help for renew
      --kube-dir string   renews ./*.conf and ./pki/*.crt for the specified --kube-dir (default "/etc/kubernetes")

Global Flags:
  -v, --verbose count   log output verbosity
```

2021-02-03 18:09 UTC, ktravis approved these changes

2021-03-08 20:59 UTC, merged